### PR TITLE
MacOS Monterey 12.3 issue resolved

### PR DESCRIPTION
**Pull request by danielcapor**
Replaced Python2 dependency with grep, python has since been removed from macos 12.3+. I also extracted the base url into a variable, as my tenant required this to be explicitly defined as https://api.us-2.crowdstrike.com/, I assume I'm not alone. Tested in production with 3 macOS Monterey devices.

### CODE REVIEW

**Comment by zensen00** [comment]
hi,

I am just triying to us this script on and keep getting errors:
_execution error: Error; SyntaxError: JSON Parse error: Unexpected EOF (-2700)
installer: ERROR - the package path specified was invalid; '/tmp/FalconSensorMacOS.pkg'.
./CSFalconInstall.sh: line 30 /Applications/Falcon.app/Contents/Resources/Falconctl: No such file or directory_

Did you exeriance this during your install and have any fixes/workarounds?

**Comment by chadb1310** [comment]
> hi,
> 
> I am just triying to us this script on and keep getting errors: _execution error: Error; SyntaxError: JSON Parse error: Unexpected EOF (-2700) installer: ERROR - the package path specified was invalid; '/tmp/FalconSensorMacOS.pkg'. ./CSFalconInstall.sh: line 30 /Applications/Falcon.app/Contents/Resources/Falconctl: No such file or directory_
> 
> Did you exeriance this during your install and have any fixes/workarounds?

I am also getting the above error? any workaround?

**Comment by cliv** [comment]
@danielcapor - Does #2 (Plus the other commits i've made to switch to OSAScript) solve your problems?

**Comment by cliv** [comment]
@zensen00 @chadb1310 - Have you tried the latest code in the main branch? I've just tested manually, and the install ran without issue.

If you're still having issues, please open an issue and we can work together to try and solve it.

**Comment by cliv** [comment]
(closing as this PR no longer merges cleanly - if there is a desire to not use OSAScript and grep instead, i'd be willing to discuss in a new PR)

**Pull request closed without merging**
